# Source files configuration

set(TARGET_SOURCES
    src/engine/component/collider_component.cpp
    src/engine/component/collider_component.h
    src/engine/component/component.h
    src/engine/component/parallax_component.cpp
    src/engine/component/parallax_component.h
    src/engine/component/physics_component.cpp
    src/engine/component/physics_component.h
    src/engine/component/sprite_component.cpp
    src/engine/component/sprite_component.h
    src/engine/component/tilelayer_component.cpp
    src/engine/component/tilelayer_component.h
    src/engine/component/transform_component.cpp
    src/engine/component/transform_component.h
    src/engine/core/config.cpp
    src/engine/core/config.h
    src/engine/core/context.cpp
    src/engine/core/context.h
    src/engine/core/game_app.cpp
    src/engine/core/game_app.h
    src/engine/core/time.cpp
    src/engine/core/time.h
    src/engine/input/input_manager.cpp
    src/engine/input/input_manager.h
    src/engine/object/game_object.cpp
    src/engine/object/game_object.h
    src/engine/physics/collider.h
    src/engine/physics/collision.cpp
    src/engine/physics/collision.h
    src/engine/physics/physics_engine.cpp
    src/engine/physics/physics_engine.h
    src/engine/render/camera.cpp
    src/engine/render/camera.h
    src/engine/render/renderer.cpp
    src/engine/render/renderer.h
    src/engine/render/sprite.h
    src/engine/resource/audio_manager.cpp
    src/engine/resource/audio_manager.h
    src/engine/resource/font_manager.cpp
    src/engine/resource/font_manager.h
    src/engine/resource/resource_manager.cpp
    src/engine/resource/resource_manager.h
    src/engine/resource/texture_manager.cpp
    src/engine/resource/texture_manager.h
    src/engine/scene/level_loader.cpp
    src/engine/scene/level_loader.h
    src/engine/scene/scene_manager.cpp
    src/engine/scene/scene_manager.h
    src/engine/scene/scene.cpp
    src/engine/scene/scene.h
    src/engine/utils/alignment.h
    src/engine/utils/assert.h
    src/engine/utils/math.h
    src/engine/utils/non_copyable.h
    src/game/game_scene.cpp
    src/game/game_scene.h
    src/log.cpp
    src/log.h
    src/main.cpp
)

set(TARGET_INCLUDE_DIRS
    src
)
