# Source files configuration

set(TARGET_SOURCES
    src/engine/core/config.h
    src/engine/core/context.cpp
    src/engine/core/context.h
    src/engine/core/game_app.cpp
    src/engine/core/game_app.h
    src/engine/core/game_state.cpp
    src/engine/core/game_state.h
    src/engine/core/time.cpp
    src/engine/core/time.h
    src/engine/ecs/components.h
    src/engine/ecs/systems.cpp
    src/engine/ecs/systems.h
    src/engine/input/input_manager.cpp
    src/engine/input/input_manager.h
    src/engine/render/animation.cpp
    src/engine/render/animation.h
    src/engine/render/camera.cpp
    src/engine/render/camera.h
    src/engine/render/renderer.cpp
    src/engine/render/renderer.h
    src/engine/render/sprite.h
    src/engine/render/text_renderer.cpp
    src/engine/render/text_renderer.h
    src/engine/resource/audio_manager.cpp
    src/engine/resource/audio_manager.h
    src/engine/resource/font_manager.cpp
    src/engine/resource/font_manager.h
    src/engine/resource/resource_manager.cpp
    src/engine/resource/resource_manager.h
    src/engine/resource/texture_manager.cpp
    src/engine/resource/texture_manager.h
    src/engine/scene/ecs_level_loader.cpp
    src/engine/scene/ecs_level_loader.h
    src/engine/scene/scene_manager.cpp
    src/engine/scene/scene_manager.h
    src/engine/scene/scene.cpp
    src/engine/scene/scene.h
    src/engine/ui/state/ui_hover_state.cpp
    src/engine/ui/state/ui_hover_state.h
    src/engine/ui/state/ui_normal_state.cpp
    src/engine/ui/state/ui_normal_state.h
    src/engine/ui/state/ui_pressed_state.cpp
    src/engine/ui/state/ui_pressed_state.h
    src/engine/ui/state/ui_state.h
    src/engine/ui/ui_button.cpp
    src/engine/ui/ui_button.h
    src/engine/ui/ui_element.cpp
    src/engine/ui/ui_element.h
    src/engine/ui/ui_image.cpp
    src/engine/ui/ui_image.h
    src/engine/ui/ui_interactive.cpp
    src/engine/ui/ui_interactive.h
    src/engine/ui/ui_label.cpp
    src/engine/ui/ui_label.h
    src/engine/ui/ui_manager.cpp
    src/engine/ui/ui_manager.h
    src/engine/ui/ui_panel.cpp
    src/engine/ui/ui_panel.h
    src/game/data/session_data.cpp
    src/game/data/session_data.h
    src/game/ecs/components.h
    src/game/ecs/entity/effect_entity.cpp
    src/game/ecs/entity/effect_entity.h
    src/game/ecs/entity/enemy_entity.cpp
    src/game/ecs/entity/enemy_entity.h
    src/game/ecs/entity/item_entity.cpp
    src/game/ecs/entity/item_entity.h
    src/game/ecs/entity/player_entity.cpp
    src/game/ecs/entity/player_entity.h
    src/game/ecs/systems.cpp
    src/game/ecs/systems.h
    src/game/scene/end_scene.cpp
    src/game/scene/end_scene.h
    src/game/scene/game_scene.cpp
    src/game/scene/game_scene.h
    src/game/scene/helps_scene.cpp
    src/game/scene/helps_scene.h
    src/game/scene/menu_scene.cpp
    src/game/scene/menu_scene.h
    src/game/scene/title_scene.cpp
    src/game/scene/title_scene.h
    src/utils/alignment.h
    src/utils/assert.h
    src/utils/log.cpp
    src/utils/log.h
    src/utils/math.h
    src/utils/non_copyable.h
    src/main.cpp)

set(TARGET_INCLUDE_DIRS src)
