# Source files configuration

set(TARGET_SOURCES
    src/engine/component/animation_component.h
    src/engine/component/collider_component.h
    src/engine/component/health_component.h
    src/engine/component/parallax_component.h
    src/engine/component/physics_component.h
    src/engine/component/sprite_component.h
    src/engine/component/tag_component.h
    src/engine/component/tilelayer_component.h
    src/engine/component/transform_component.h
    src/engine/core/config.h
    src/engine/core/context.cpp
    src/engine/core/context.h
    src/engine/core/game_app.cpp
    src/engine/core/game_app.h
    src/engine/core/game_state.cpp
    src/engine/core/game_state.h
    src/engine/core/time.cpp
    src/engine/core/time.h
    src/engine/input/input_manager.cpp
    src/engine/input/input_manager.h
    src/engine/render/animation.cpp
    src/engine/render/animation.h
    src/engine/render/camera.cpp
    src/engine/render/camera.h
    src/engine/render/renderer.cpp
    src/engine/render/renderer.h
    src/engine/render/sprite.h
    src/engine/render/text_renderer.cpp
    src/engine/render/text_renderer.h
    src/engine/resource/audio_manager.cpp
    src/engine/resource/audio_manager.h
    src/engine/resource/font_manager.cpp
    src/engine/resource/font_manager.h
    src/engine/resource/resource_manager.cpp
    src/engine/resource/resource_manager.h
    src/engine/resource/texture_manager.cpp
    src/engine/resource/texture_manager.h
    src/engine/scene/scene_manager.cpp
    src/engine/scene/scene_manager.h
    src/engine/scene/scene.cpp
    src/engine/scene/scene.h
    src/engine/system/physics_engine.cpp
    src/engine/system/physics_engine.h
    src/engine/ui/state/ui_hover_state.cpp
    src/engine/ui/state/ui_hover_state.h
    src/engine/ui/state/ui_normal_state.cpp
    src/engine/ui/state/ui_normal_state.h
    src/engine/ui/state/ui_pressed_state.cpp
    src/engine/ui/state/ui_pressed_state.h
    src/engine/ui/state/ui_state.h
    src/engine/ui/ui_button.cpp
    src/engine/ui/ui_button.h
    src/engine/ui/ui_element.cpp
    src/engine/ui/ui_element.h
    src/engine/ui/ui_image.cpp
    src/engine/ui/ui_image.h
    src/engine/ui/ui_interactive.cpp
    src/engine/ui/ui_interactive.h
    src/engine/ui/ui_label.cpp
    src/engine/ui/ui_label.h
    src/engine/ui/ui_manager.cpp
    src/engine/ui/ui_manager.h
    src/engine/ui/ui_panel.cpp
    src/engine/ui/ui_panel.h
    src/utils/alignment.h
    src/utils/assert.h
    src/utils/collision.h
    src/utils/log.cpp
    src/utils/log.h
    src/utils/math.h
    src/utils/non_copyable.h
    src/main.cpp)

set(TARGET_INCLUDE_DIRS src)
